# Generated by Django 5.0.3 on 2026-04-27 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metro', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('facility', 'Cơ sở vật chất'), ('experience', 'Trải nghiệm'), ('error', 'Lỗi')], max_length=30)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('resolved', 'Đã giải quyết'), ('rejected', 'Đã từ chối')], default='pending', max_length=30)),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('train', models.ForeignKey(blank=True, db_column='train_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='metro.train')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.user')),
            ],
            options={
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
