# Generated by Django 5.0.3 on 2026-04-27 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('icon_svg', models.TextField(blank=True, null=True)),
                ('color_hex', models.CharField(blank=True, max_length=10, null=True)),
                ('bg_color_hex', models.CharField(blank=True, max_length=10, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'amenity_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AmenityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'amenity_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('color_hex', models.CharField(blank=True, max_length=10, null=True)),
                ('stroke_weight', models.IntegerField(blank=True, null=True)),
                ('geojson_coordinates', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metro_lines',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('sequence_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(blank=True, db_column='line_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='metro.metroline')),
            ],
            options={
                'db_table': 'stations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BusStopCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('routes', models.JSONField(blank=True, null=True)),
                ('distance_to_station', models.IntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(blank=True, db_column='station_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_stops', to='metro.station')),
            ],
            options={
                'db_table': 'bus_stop_cache',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=255)),
                ('distance_meters', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenities', to='metro.amenitycategory')),
                ('amenity_type', models.ForeignKey(blank=True, db_column='amenity_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_amenities', to='metro.amenitytype')),
                ('station', models.ForeignKey(blank=True, db_column='station_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='metro.station')),
            ],
            options={
                'db_table': 'amenities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('manufacture_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('outbound', 'Lượt đi'), ('inbound', 'Lượt về')], default='outbound', max_length=20)),
                ('is_simulated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_station', models.ForeignKey(blank=True, db_column='current_station_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_trains', to='metro.station')),
                ('line', models.ForeignKey(db_column='line_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metro.metroline')),
            ],
            options={
                'db_table': 'trains',
                'managed': True,
            },
        ),
    ]
