# Generated by Django 5.0.3 on 2026-04-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='current_station',
            field=models.ForeignKey(blank=True, db_column='current_station_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_trains', to='metro.station'),
        ),
    ]
