# Generated by Django 5.0.3 on 2026-04-27

import json
from pathlib import Path

import django.db.models.deletion
from django.db import migrations, models


def fix_mojibake(value):
    if isinstance(value, dict):
        return {fix_mojibake(key): fix_mojibake(item) for key, item in value.items()}
    if isinstance(value, list):
        return [fix_mojibake(item) for item in value]
    if isinstance(value, str):
        try:
            repaired = value.encode("latin1").decode("utf-8")
        except (UnicodeEncodeError, UnicodeDecodeError):
            return value
        return repaired
    return value


def load_bus_stops(apps, schema_editor):
    BusStop = apps.get_model("metro", "BusStop")
    Station = apps.get_model("metro", "Station")

    project_root = Path(__file__).resolve().parents[4]
    json_path = project_root / "tram_xe_buyt_gan_ga_metro_HCMC.json"
    if not json_path.exists():
        return

    with json_path.open("r", encoding="utf-8") as source:
        payload = fix_mojibake(json.load(source))

    station_by_code = {station.code: station for station in Station.objects.all()}
    rows = payload.get("tram_xe_buyt_gan_ga_metro", [])

    bus_stops = []
    for item in rows:
        station_code = str(item.get("Mã ga", "")).strip()
        station = station_by_code.get(station_code)
        routes = [
            route.strip()
            for route in str(item.get("Tuyến xe buýt kết nối", "")).split(",")
            if route.strip()
        ]
        bus_stops.append(
            BusStop(
                code=f"BUS-{int(item.get('STT', 0)):03d}",
                name=str(item.get("Tên trạm xe buýt", "")).strip(),
                latitude=item.get("Vĩ độ (Latitude)"),
                longitude=item.get("Kinh độ (Longitude)"),
                address=str(item.get("Địa chỉ", "")).strip() or None,
                routes=routes,
                station=station,
                distance_to_station=item.get("Khoảng cách tới ga (m)"),
                stop_type=str(item.get("Loại trạm", "")).strip() or None,
                note=str(item.get("Ghi chú", "")).strip() or None,
                is_active=True,
            )
        )

    if bus_stops:
        BusStop.objects.bulk_create(bus_stops, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("metro", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BusStopCache",
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("routes", models.JSONField(blank=True, null=True)),
                ("distance_to_station", models.IntegerField(blank=True, null=True)),
                ("stop_type", models.CharField(blank=True, max_length=120, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        db_column="station_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bus_stops",
                        to="metro.station",
                    ),
                ),
            ],
            options={
                "db_table": "bus_stops",
                "managed": True,
            },
        ),
        migrations.RunPython(load_bus_stops, migrations.RunPython.noop),
    ]
