# Generated by Django 5.0.3 on 2026-05-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_replace_bus_stop_cache_with_bus_stops'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Lượt đi (BT → ST)'), ('inbound', 'Lượt về (ST → BT)')], max_length=20)),
                ('trip_run', models.CharField(db_index=True, max_length=100)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, related_name='train_logs', to='metro.station')),
                ('train', models.ForeignKey(db_column='train_id', on_delete=django.db.models.deletion.CASCADE, related_name='station_logs', to='metro.train')),
            ],
            options={
                'db_table': 'train_station_logs',
                'ordering': ['-arrived_at'],
                'managed': True,
                'unique_together': {('train', 'station', 'trip_run')},
            },
        ),
    ]
