# Generated by Django 5.0.3 on 2026-04-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0003_amenity_address_en_amenity_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='opening_hours_en',
        ),
        migrations.RemoveField(
            model_name='amenitycategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='amenitytype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='metroline',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='metroline',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='station',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='station',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='station',
            name='name_en',
        ),
    ]
