// src/lib/mock-data.ts (append amenities section)

import { Amenity, MetroStation } from '@/types/amenity';

export const MOCK_STATIONS: MetroStation[] = [
  { id: 'BT', name: 'Ga Bến Thành', nameEn: 'Ben Thanh Station', line: 'L1' },
  { id: 'NHTP', name: 'Ga Nhà hát Thành phố', nameEn: 'Opera House Station', line: 'L1' },
  { id: 'BS', name: 'Ga Ba Son', nameEn: 'Ba Son Station', line: 'L1' },
  { id: 'VT', name: 'Ga Văn Thánh', nameEn: 'Van Thanh Station', line: 'L1' },
  { id: 'PL', name: 'Ga Phước Long', nameEn: 'Phuoc Long Station', line: 'L1' },
  { id: 'BThai', name: 'Ga Bình Thái', nameEn: 'Binh Thai Station', line: 'L1' },
  { id: 'TDu', name: 'Ga Thủ Đức', nameEn: 'Thu Duc Station', line: 'L1' },
  { id: 'KCNC', name: 'Ga Khu Công Nghệ Cao', nameEn: 'Hi-Tech Park Station', line: 'L1' },
  { id: 'ST', name: 'Ga Suối Tiên', nameEn: 'Suoi Tien Station', line: 'L1' },
];

export const MOCK_AMENITIES: Amenity[] = [
  {
    id: '1',
    name: 'Chợ Bến Thành',
    type: 'service',
    address: 'Lê Lợi, P. Bến Thành',
    stationId: 'BT',
    stationName: 'Ga Bến Thành',
    imageUrl: 'https://images.unsplash.com/photo-1555212697-194d092e3b8f?w=600',
    description: 'Chợ truyền thống nổi tiếng tại trung tâm Sài Gòn',
  },
  {
    id: '2',
    name: 'New World Saigon Hotel',
    type: 'hotel',
    address: '76 Đường Lê Lai, Phường Bến Thành, Thành phố Hồ Chí Minh, Việt Nam',
    stationId: 'BT',
    stationName: 'Ga Bến Thành',
    distanceMeters: 250,
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600',
    rating: 4.5,
    openingHours: '24/7',
  },
  {
    id: '3',
    name: 'Nhà hát Thành phố',
    type: 'service',
    address: '7 Công Trường Lam Sơn',
    stationId: 'NHTP',
    stationName: 'Ga Nhà hát Thành phố',
    imageUrl: 'https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=600',
    description: 'Nhà hát opera biểu tượng của Sài Gòn',
  },
  {
    id: '4',
    name: 'The Coffee House',
    type: 'cafe',
    address: '86 Đường Cao Thắng, Quận 3',
    stationId: 'BT',
    stationName: 'Ga Bến Thành',
    distanceMeters: 380,
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
    rating: 4.3,
    openingHours: '07:00 - 23:00',
  },
  {
    id: '5',
    name: 'Phúc Long Coffee & Tea',
    type: 'cafe',
    address: '42 Nguyễn Huệ, Quận 1',
    stationId: 'NHTP',
    stationName: 'Ga Nhà hát Thành phố',
    distanceMeters: 150,
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600',
    rating: 4.4,
    openingHours: '06:30 - 22:30',
  },
  {
    id: '6',
    name: 'Nhà hàng Ngon',
    type: 'restaurant',
    address: '160 Pasteur, Quận 3',
    stationId: 'BT',
    stationName: 'Ga Bến Thành',
    distanceMeters: 420,
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600',
    rating: 4.6,
    openingHours: '10:00 - 22:00',
  },
  {
    id: '7',
    name: 'Vincom Center Bến Thành',
    type: 'shopping',
    address: '72 Lê Thánh Tôn, Quận 1',
    stationId: 'NHTP',
    stationName: 'Ga Nhà hát Thành phố',
    distanceMeters: 300,
    imageUrl: 'https://images.unsplash.com/photo-1581417478175-a9ef18f210c2?w=600',
    rating: 4.5,
    openingHours: '09:30 - 22:00',
  },
  {
    id: '8',
    name: 'Rex Hotel Saigon',
    type: 'hotel',
    address: '141 Nguyễn Huệ, Quận 1',
    stationId: 'NHTP',
    stationName: 'Ga Nhà hát Thành phố',
    distanceMeters: 200,
    imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600',
    rating: 4.4,
    openingHours: '24/7',
  },
  {
    id: '9',
    name: 'Pizza 4P\'s Lê Thánh Tôn',
    type: 'restaurant',
    address: '8 Thủ Khoa Huân, Phường Bến Thành, Quận 1',
    stationId: 'BT',
    stationName: 'Ga Bến Thành',
    distanceMeters: 180,
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600',
    rating: 4.7,
    openingHours: '11:00 - 22:30',
  },
  {
    id: '10',
    name: 'Saigon Centre',
    type: 'shopping',
    address: '65 Lê Lợi, Phường Bến Thành, Quận 1',
    stationId: 'BT',
    stationName: 'Ga Bến Thành',
    distanceMeters: 100,
    imageUrl: 'https://images.unsplash.com/photo-1519567241314-87e6f4648b51?w=600',
    rating: 4.3,
    openingHours: '10:00 - 22:00',
  },
  {
    id: '11',
    name: 'Highlands Coffee',
    type: 'cafe',
    address: 'Tầng 1, Vincom Center, 72 Lê Thánh Tôn',
    stationId: 'NHTP',
    stationName: 'Ga Nhà hát Thành phố',
    distanceMeters: 300,
    imageUrl: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=600',
    rating: 4.1,
    openingHours: '07:00 - 23:00',
  },
  {
    id: '12',
    name: 'Bưu điện Thành phố',
    type: 'service',
    address: '2 Công Xã Paris, Bến Nghé, Quận 1',
    stationId: 'NHTP',
    stationName: 'Ga Nhà hát Thành phố',
    distanceMeters: 400,
    imageUrl: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=600',
    description: 'Công trình kiến trúc lịch sử của Sài Gòn',
  },
];
